### PR TITLE
Add gh actions

### LINKED ISSUE #1: automate game ID crosswalk and advanced passing
- Run once per week: https://github.com/guga31bb/pfr_scrapR/blob/master/R/pfr_game_id_crosswalk.R
- Run once per day during season: https://github.com/guga31bb/pfr_scrapR/blob/master/R/passing.R

To add: script to get snap counts for an ongoing season

### PR DESCRIPTION
**Pull request by mrcaseb**
The schedule parts in the actions are commented out currently because the repo is private. Private repos have limited runtime so I wouldn't run them until we think we are ready.

closes #1

### CODE REVIEW

**Comment by mrcaseb** [comment]
The passing stats actions will be scheduled to run in Jan, Feb, Sep-Dec

Would you like to do the same for game ids?

**Comment by mrcaseb** [comment]
Oh and I also added some standard gitignore stuff

**Comment by guga31bb** [comment]
I made the repo public yesterday- is that not showing up for you?

**Comment by guga31bb** [comment]
And yes there's no reason to update the game IDs over the offseason, so Jan-Feb & Sep-Dec sounds good

**Comment by mrcaseb** [comment]
> I made the repo public yesterday- is that not showing up for you?

Oh I missed that, sorry

**Comment by guga31bb** [comment]
Ok to accept? ty for doing this!

**Pull request merged**
